name: live-geluid.be
favicon: null
layout_spectrum: 0.3808972272090614
typography_spectrum: 0.5878218770958483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3971835719421506
  lightness: 0.15522611839696765
  saturation: 0.5888934785034508
  rhythmicContrast: 0.5932061816565692
purpose: []
